contracts/ProxyFactory.sol, contracts/test/mocks/Mocks.sol
=> chore: _implementation -> _implementationOf

contracts/ProxyFactory.sol, contracts/test/mocks/Mocks.sol
=> fix: require in _newInstanceWithSalt and more functional

contracts/Proxied.sol, contracts/ProxyFactory.sol, contracts/SlotManipulatable.sol, contracts/interfaces/IProxied.sol, contracts/test/SlotManipulatable.t.sol, contracts/test/Test.t.sol, contracts/test/mocks/Mocks.sol
=> chore: Standardize Argument Styles

contracts/Proxied.sol, contracts/Proxy.sol, contracts/ProxyFactory.sol, contracts/SlotManipulatable.sol, contracts/interfaces/IProxied.sol, contracts/test/mocks/Mocks.sol
- IProxied natspec
- tighter and clearer proxy factory code
- removed all requires from internal proxy factory functions
- reordered some function
=> refactor: More Cleanup

contracts/interfaces/IProxied.sol
=> chore: Critical ACL warning in natspec

contracts/Proxied.sol, contracts/interfaces/IProxied.sol, contracts/test/mocks/Mocks.sol
=> feat: Remove requires from Proxied

contracts/test/mocks/Mocks.sol
=> chore: Mock fix

contracts/ProxyFactory.sol, contracts/test/Test.t.sol, contracts/test/mocks/Mocks.sol
=> feat: `_isInstance`

contracts/Proxied.sol, contracts/Proxy.sol, contracts/ProxyFactory.sol, contracts/test/SlotManipulatable.t.sol, contracts/test/Test.t.sol, contracts/test/mocks/Mocks.sol
=> fix: Remove erroneous `isInstance`

contracts/Proxy.sol, contracts/ProxyFactory.sol, contracts/test/Test.t.sol
=> feat: Simplified Proxy deployment

config/ci.json, config/dev.json, contracts/Proxy.sol, contracts/ProxyFactory.sol, contracts/interfaces/IDefaultImplementationBeacon.sol, contracts/test/ProxyFactory.t.sol, contracts/test/SlotManipulatable.t.sol, contracts/test/mocks/Mocks.sol
=> feat: Cleanup and Better Determinism

contracts/Proxy.sol, contracts/test/ProxyFactory.t.sol, contracts/test/mocks/Mocks.sol
=> fix: Add contract check on fallback

contracts/ProxyFactory.sol, contracts/test/ProxyFactory.t.sol
=> fix: Added protection to avoid double register implementation

contracts/ProxyFactory.sol, contracts/test/ProxyFactory.t.sol
=> feat: Added missing unit tests (SC-4141)

contracts/Proxy.sol, contracts/ProxyFactory.sol, contracts/test/ProxyFactory.t.sol
Addresses https://github.com/code-423n4/2021-12-maple-findings/issues/15
=> fix: Constructor validation in Proxy (C4 #15)

README.md, contracts/Proxied.sol, contracts/Proxy.sol, contracts/ProxyFactory.sol, contracts/SlotManipulatable.sol, contracts/interfaces/IDefaultImplementationBeacon.sol, contracts/interfaces/IProxied.sol, contracts/test/ProxyFactory.t.sol, contracts/test/SlotManipulatable.t.sol, contracts/test/mocks/Mocks.sol
=> formatting: Update solc, param underscores, licensing

contracts/Proxy.sol, contracts/ProxyFactory.sol, contracts/test/ProxyFactory.t.sol
=> feat: Use `code.length` instead of `extcodesize`

README.md
=> feat: README update (SC-4527)

README.md
=> chore: Update README (SC-4648)

README.md
=> feat: Update bug bounty info in README (SC-4666)

.gitmodules, contracts/test/ProxyFactory.t.sol, contracts/test/SlotManipulatable.t.sol
- add contract-test-utils and remove ds-test
=> chore: add ctu
